version: '3'

services:
  client-classik:
    image: cloudprojectvinci.azurecr.io/cloudprojectsupdevinci/client:1.1
    build:
      context: .
      dockerfile: ./apps/client/classik/Dockerfile
    ports:
      - 4200:4200
    networks:
      - public

  api-klassiq:
    image: cloudprojectvinci.azurecr.io/cloudprojectsupdevinci/api:1.1
    build:
      context: .
      dockerfile: ./apps/api/klassiq/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - public
      - private
      
  mongo:
    image: mongo
    volumes:
      - mongo:/usr/src/app
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGO_INITDB_USER_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_USER_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  node_modules:
  mongo:

networks:
  private:
  public:
    # name: traefik_webgateway
    # external: true