version: '3'

services:
  client-classik:
    image: cloudprojectvinci.azurecr.io/cloudprojectsupdevinci/client:1.1
    container_name: cloudprojectvinci-client
    domainname: cloudgaming
    ports:
      - 80:80

  api-klassiq:
    image: cloudprojectvinci.azurecr.io/cloudprojectsupdevinci/api:1.1
    container_name: cloudprojectvinci-api
    domainname: cloudgaming
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGO_INITDB_USER_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_USER_PASSWORD: ${DATABASE_PASSWORD}